[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agsense-agent-retrieval"
version = "0.1.0"
description = "AgSense Retrieval Agent - Data retrieval and search"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "AgSense Team", email = "team@agsense.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "structlog>=23.2.0",
    "tenacity>=8.2.3",
    "httpx>=0.25.0",
    "agsense-core",
]

[tool.uv.sources]
agsense-core = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/agent_retrieval"]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.0",
    "mypy>=1.8.0",
    "ruff>=0.1.0",
    "black>=23.12.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.0",
    "mypy>=1.8.0",
    "ruff>=0.1.0",
    "black>=23.12.0",
]
