---
service: api-gateway
objective: p99_latency_ms
target: 450
window: "7d"
baseline:
  source: "prom: histogram_quantile(0.99, rate(http_request_duration_ms_bucket{service='api-gateway'}[5m]))"
  keepHistory: 90d
