name: Resilience Gate
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          if ! command -v opa >/dev/null 2>&1; then
            curl -L -o opa https://openpolicyagent.org/downloads/v0.68.0/opa_linux_amd64_static
            chmod +x ./opa && sudo mv ./opa /usr/local/bin/opa
          fi
      - name: Lint YAML
        run: yamllint configs
      - name: Validate configs
        run: python scripts/validate_configs.py
      - name: Policy tests
        run: opa test platform/gatekeeper/policies -v
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resilience-artifacts
          path: |
            configs
            platform/gatekeeper/policies