name: Resilience Gate (main)

on:
  workflow_dispatch:
    inputs:
      force_slo:
        description: "Simulate SLO regressions (integer). 0 = none"
        required: false
        default: "0"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gate:
    name: OPA Resilience Gate
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools (jq, Python deps)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install yamllint jsonschema

      - name: Install OPA (v0.68.0)
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.68.0/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa
          opa version

      - name: Lint & validate configs
        run: |
          yamllint configs
          python scripts/validate_configs.py

      - name: Run OPA policy unit tests
        run: |
          opa test platform/gatekeeper/policies -v

      - name: Build SLO input
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          FORCE_SLO_REGRESSIONS="${{ github.event.inputs.force_slo || '' }}"
          export FORCE_SLO_REGRESSIONS="${FORCE_SLO_REGRESSIONS}"
          python scripts/slo_ingest.py
          echo "SLO input:" && cat /tmp/slo.json

      - name: Enforce resilience policy
        run: |
          opa eval -f json -i /tmp/slo.json -d platform/gatekeeper/policies 'data.resilience.deny' \
            | jq -r '.result[0].expressions[0].value' > /tmp/deny.json
          echo "OPA deny set:" && cat /tmp/deny.json
          if [ "$(jq 'length' /tmp/deny.json)" -gt 0 ]; then
            echo "❌ Resilience policy denies this change"
            exit 1
          fi
